# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.CharField(max_length=200, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcomment',
            field=models.CharField(max_length=200, verbose_name='评论量'),
        ),
    ]
